# Generated by Django 4.2.3 on 2023-07-12 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('passwordCon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('lpg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hydrogen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('serial_number_esp32', models.CharField(max_length=50)),
                ('dispositive_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.dispositive')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phones_number', models.CharField(max_length=20)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.admin')),
            ],
        ),
        migrations.AddField(
            model_name='dispositive',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.manager'),
        ),
    ]
