# Generated by Django 4.2.3 on 2023-07-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_admin_passwordcon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
