# Generated by Django 4.2.3 on 2023-07-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_admin_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phones_number',
            field=models.CharField(max_length=200),
        ),
    ]
