# Generated by Django 4.2.3 on 2023-07-13 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_admin_email_alter_admin_name_alter_admin_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositive',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RemoveField(
            model_name='dispositive',
            name='manager_id',
        ),
        migrations.AddField(
            model_name='manager',
            name='dispositive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.dispositive'),
            preserve_default=False,
        ),
    ]
