# Generated by Django 4.2.3 on 2023-07-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_rename_admin_id_dispositive_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositive',
            name='alias',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
