# Generated by Django 4.2.3 on 2023-07-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_manager_password_alter_manager_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measures',
            old_name='dispositive_id',
            new_name='dispositive',
        ),
    ]
