# Generated by Django 4.2.3 on 2023-07-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_rename_dispositive_id_measures_dispositive'),
    ]

    operations = [
        migrations.AddField(
            model_name='measures',
            name='error',
            field=models.IntegerField(default=0),
        ),
    ]
